backend:
  name: git-gateway
  branch: main

media_folder: "img"
public_folder: "/img"

collections:
  - name: "pagina"
    label: "Página Conmemorativa"
    files:
      - file: "data/pagina.json"
        label: "Contenido"
        name: "contenido"
        fields:
          - { label: "Nombre", name: "nombre", widget: "string" }
          - { label: "Fechas", name: "fechas", widget: "string" }
          - { label: "Frase", name: "frase", widget: "text" }
          - { label: "Enlace de video", name: "video", widget: "string" }
          - { label: "Ubicación", name: "ubicacion", widget: "string" }
          - { label: "Imagen", name: "imagen", widget: "image" }
